#!/usr/bin/env node
const rootPath = require("app-root-path").path;
const fs = require("fs-extra");
const { join } = require("path");
const { execSync } = require("child_process");

fs.copySync(join(__dirname, "/template/copy/"), rootPath);
execSync("yarn install", { stdio: ["ignore", "inherit", "inherit"] });
